@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWNhYjc5NThjODA4OTU4MmRkOTAyMjg2IiwiaWF0IjoxNTU0NzgyMDc5LCJleHAiOjE1NTQ3OTIwNzl9.yNhTJp5lKuHWt5vAihGRv8wfKa1nburs-lvmnYkvqG4

POST http://localhost:3000/routev1/users HTTP/1.1
Content-Type: application/json

{
    "email": "rawa@variableassign.com",
    "password": "asdf"
}

###

POST http://localhost:3000/routev1/users/signin HTTP/1.1
Content-Type: application/json

{
    "email": "carterCarter@variableassign.com",
    "password": "asdf"
}

###

GET http://localhost:3000/routev1/users HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "email": "carterCarter@variableassign.com",
    "password": "asdf"
}

###
# USER ACCESS AUTH BOOK ROUTE

GET http://localhost:3000/routev1/books HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###
# SEED DATA

POST http://localhost:3000/routev1/users/seed HTTP/1.1
Content-Type: application/json

{
    "name": "Radleaf Technology",
    "email": "mariam@variableassign.com",
    "domain": "variableassign.pox",
    "isbn": "978-93-92293-01-7",
    "title":"variable Title",
    "author": "Tyler Canton"
}

